# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'specton.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(675, 652)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle("Specton Audio Analyser")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/017_headphones_Mjt_5.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(16, 16))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setContentsMargins(5, 0, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.filterBox = QtWidgets.QLineEdit(self.centralwidget)
        self.filterBox.setObjectName("filterBox")
        self.horizontalLayout_2.addWidget(self.filterBox)
        self.filter_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.filter_comboBox.setObjectName("filter_comboBox")
        self.filter_comboBox.addItem("")
        self.filter_comboBox.addItem("")
        self.filter_comboBox.addItem("")
        self.filter_comboBox.addItem("")
        self.filter_comboBox.addItem("")
        self.filter_comboBox.addItem("")
        self.filter_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.filter_comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(549, 100))
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableWidget.setAcceptDrops(True)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableWidget)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.scanButton = QtWidgets.QPushButton(self.centralwidget)
        self.scanButton.setObjectName("scanButton")
        self.horizontalLayout.addWidget(self.scanButton, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 675, 21))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.toolBar.setWindowTitle("toolBar")
        self.toolBar.setIconSize(QtCore.QSize(48, 48))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionScan_Files = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/285-play3.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionScan_Files.setIcon(icon1)
        self.actionScan_Files.setObjectName("actionScan_Files")
        self.actionStop = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/287-stop2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon2)
        self.actionStop.setObjectName("actionStop")
        self.actionFolder_Select = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/049-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFolder_Select.setIcon(icon3)
        self.actionFolder_Select.setText("Folder Select")
        self.actionFolder_Select.setObjectName("actionFolder_Select")
        self.actionClear_Filelist = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/102-undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear_Filelist.setIcon(icon4)
        self.actionClear_Filelist.setObjectName("actionClear_Filelist")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/277-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon5)
        self.actionExit.setText("Exit")
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/269-info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon6)
        self.actionAbout.setText("About")
        self.actionAbout.setObjectName("actionAbout")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/150-cogs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOptions.setIcon(icon7)
        self.actionOptions.setText("Options")
        self.actionOptions.setObjectName("actionOptions")
        self.actionViewLogDir = QtWidgets.QAction(MainWindow)
        self.actionViewLogDir.setIcon(icon3)
        self.actionViewLogDir.setText("Logs")
        self.actionViewLogDir.setObjectName("actionViewLogDir")
        self.actionViewConfigDir = QtWidgets.QAction(MainWindow)
        self.actionViewConfigDir.setIcon(icon3)
        self.actionViewConfigDir.setText("Config files")
        self.actionViewConfigDir.setObjectName("actionViewConfigDir")
        self.actionTools_Downloader = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/097-download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTools_Downloader.setIcon(icon8)
        self.actionTools_Downloader.setText("Tools Downloader")
        self.actionTools_Downloader.setObjectName("actionTools_Downloader")
        self.toolBar.addAction(self.actionFolder_Select)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionScan_Files)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClear_Filelist)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOptions)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_2.setText(_translate("MainWindow", "Filter:"))
        self.filter_comboBox.setItemText(0, _translate("MainWindow", "All"))
        self.filter_comboBox.setItemText(1, _translate("MainWindow", "Errors only"))
        self.filter_comboBox.setItemText(2, _translate("MainWindow", "Lossless"))
        self.filter_comboBox.setItemText(3, _translate("MainWindow", "Lossy"))
        self.filter_comboBox.setItemText(4, _translate("MainWindow", "High quality"))
        self.filter_comboBox.setItemText(5, _translate("MainWindow", "Low quality"))
        self.filter_comboBox.setItemText(6, _translate("MainWindow", "Unscanned"))
        self.tableWidget.setSortingEnabled(True)
        self.label.setText(_translate("MainWindow", "Drag audio files or folders into box above then click scan"))
        self.scanButton.setText(_translate("MainWindow", "Scan"))
        self.actionScan_Files.setText(_translate("MainWindow", "Scan Files"))
        self.actionScan_Files.setToolTip(_translate("MainWindow", "Scan Files"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionClear_Filelist.setText(_translate("MainWindow", "Clear Filelist"))
        self.actionViewLogDir.setToolTip(_translate("MainWindow", "Open Log Directory"))
        self.actionViewConfigDir.setToolTip(_translate("MainWindow", "Open Config Directory"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

