# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_optionsDialog(object):
    def setupUi(self, optionsDialog):
        optionsDialog.setObjectName("optionsDialog")
        optionsDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        optionsDialog.resize(562, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/150-cogs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        optionsDialog.setWindowIcon(icon)
        optionsDialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(optionsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(370, 440, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(optionsDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 371, 231))
        self.groupBox.setObjectName("groupBox")
        self.checkBox_followsymlinks = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_followsymlinks.setGeometry(QtCore.QRect(160, 80, 101, 17))
        self.checkBox_followsymlinks.setObjectName("checkBox_followsymlinks")
        self.checkBox_recursive = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_recursive.setGeometry(QtCore.QRect(10, 80, 151, 17))
        self.checkBox_recursive.setObjectName("checkBox_recursive")
        self.checkBox_cache = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_cache.setGeometry(QtCore.QRect(10, 110, 111, 17))
        self.checkBox_cache.setObjectName("checkBox_cache")
        self.lineEdit_filemaskregex = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_filemaskregex.setGeometry(QtCore.QRect(10, 40, 351, 20))
        self.lineEdit_filemaskregex.setObjectName("lineEdit_filemaskregex")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 181, 16))
        self.label_3.setObjectName("label_3")
        self.spinBox_processes = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_processes.setGeometry(QtCore.QRect(250, 140, 42, 22))
        self.spinBox_processes.setMinimum(0)
        self.spinBox_processes.setMaximum(200)
        self.spinBox_processes.setObjectName("spinBox_processes")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 241, 21))
        self.label_4.setObjectName("label_4")
        self.checkBox_cacheraw = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_cacheraw.setGeometry(QtCore.QRect(110, 110, 151, 17))
        self.checkBox_cacheraw.setObjectName("checkBox_cacheraw")
        self.checkBox_aucdtect_scan = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_aucdtect_scan.setGeometry(QtCore.QRect(10, 180, 171, 17))
        self.checkBox_aucdtect_scan.setObjectName("checkBox_aucdtect_scan")
        self.horizontalSlider_aucdtect_mode = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_aucdtect_mode.setGeometry(QtCore.QRect(70, 200, 61, 16))
        self.horizontalSlider_aucdtect_mode.setMaximum(40)
        self.horizontalSlider_aucdtect_mode.setSliderPosition(8)
        self.horizontalSlider_aucdtect_mode.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_aucdtect_mode.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_aucdtect_mode.setTickInterval(10)
        self.horizontalSlider_aucdtect_mode.setObjectName("horizontalSlider_aucdtect_mode")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(140, 200, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.groupBox_2 = QtWidgets.QGroupBox(optionsDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 10, 161, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_debug = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_debug.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.checkBox_debug.setObjectName("checkBox_debug")
        self.groupBox_3 = QtWidgets.QGroupBox(optionsDialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 249, 341, 221))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 70, 171, 16))
        self.label.setObjectName("label")
        self.lineEdit_mediainfo_path = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_mediainfo_path.setGeometry(QtCore.QRect(10, 40, 281, 20))
        self.lineEdit_mediainfo_path.setObjectName("lineEdit_mediainfo_path")
        self.lineEdit_mp3guessenc_path = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_mp3guessenc_path.setGeometry(QtCore.QRect(10, 90, 281, 20))
        self.lineEdit_mp3guessenc_path.setObjectName("lineEdit_mp3guessenc_path")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 171, 16))
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 171, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_sox_path = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_sox_path.setGeometry(QtCore.QRect(10, 140, 281, 20))
        self.lineEdit_sox_path.setObjectName("lineEdit_sox_path")
        self.lineEdit_ffprobe_path = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_ffprobe_path.setGeometry(QtCore.QRect(10, 190, 281, 20))
        self.lineEdit_ffprobe_path.setObjectName("lineEdit_ffprobe_path")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 170, 171, 16))
        self.label_11.setObjectName("label_11")
        self.pushButton_mediainfo_path = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_mediainfo_path.setGeometry(QtCore.QRect(300, 40, 21, 23))
        self.pushButton_mediainfo_path.setAutoDefault(True)
        self.pushButton_mediainfo_path.setDefault(False)
        self.pushButton_mediainfo_path.setFlat(False)
        self.pushButton_mediainfo_path.setObjectName("pushButton_mediainfo_path")
        self.pushButton_mp3guessenc_path = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_mp3guessenc_path.setGeometry(QtCore.QRect(300, 90, 21, 23))
        self.pushButton_mp3guessenc_path.setAutoDefault(True)
        self.pushButton_mp3guessenc_path.setDefault(False)
        self.pushButton_mp3guessenc_path.setFlat(False)
        self.pushButton_mp3guessenc_path.setObjectName("pushButton_mp3guessenc_path")
        self.pushButton_sox_path = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_sox_path.setGeometry(QtCore.QRect(300, 140, 21, 23))
        self.pushButton_sox_path.setAutoDefault(True)
        self.pushButton_sox_path.setDefault(False)
        self.pushButton_sox_path.setFlat(False)
        self.pushButton_sox_path.setObjectName("pushButton_sox_path")
        self.groupBox_4 = QtWidgets.QGroupBox(optionsDialog)
        self.groupBox_4.setGeometry(QtCore.QRect(390, 90, 161, 251))
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkBox_savewindowstate = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_savewindowstate.setGeometry(QtCore.QRect(10, 20, 141, 21))
        self.checkBox_savewindowstate.setObjectName("checkBox_savewindowstate")
        self.checkBox_clearfilelist = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_clearfilelist.setGeometry(QtCore.QRect(10, 40, 141, 31))
        self.checkBox_clearfilelist.setObjectName("checkBox_clearfilelist")
        self.checkBox_spectrogram = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_spectrogram.setGeometry(QtCore.QRect(10, 70, 141, 31))
        self.checkBox_spectrogram.setObjectName("checkBox_spectrogram")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(40, 100, 81, 16))
        self.label_8.setObjectName("label_8")
        self.spinBox_spectrogram_palette = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_spectrogram_palette.setGeometry(QtCore.QRect(80, 130, 42, 22))
        self.spinBox_spectrogram_palette.setMinimum(1)
        self.spinBox_spectrogram_palette.setMaximum(6)
        self.spinBox_spectrogram_palette.setObjectName("spinBox_spectrogram_palette")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(20, 130, 61, 16))
        self.label_9.setObjectName("label_9")
        self.checkBox_bitrate_graph = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_bitrate_graph.setGeometry(QtCore.QRect(10, 160, 141, 31))
        self.checkBox_bitrate_graph.setObjectName("checkBox_bitrate_graph")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(40, 190, 91, 16))
        self.label_10.setObjectName("label_10")
        self.pushButton_ffprobe_path = QtWidgets.QPushButton(optionsDialog)
        self.pushButton_ffprobe_path.setGeometry(QtCore.QRect(310, 440, 21, 23))
        self.pushButton_ffprobe_path.setAutoDefault(True)
        self.pushButton_ffprobe_path.setDefault(False)
        self.pushButton_ffprobe_path.setFlat(False)
        self.pushButton_ffprobe_path.setObjectName("pushButton_ffprobe_path")

        self.retranslateUi(optionsDialog)
        self.buttonBox.accepted.connect(optionsDialog.accept)
        self.buttonBox.rejected.connect(optionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(optionsDialog)

    def retranslateUi(self, optionsDialog):
        _translate = QtCore.QCoreApplication.translate
        optionsDialog.setWindowTitle(_translate("optionsDialog", "Options"))
        self.groupBox.setTitle(_translate("optionsDialog", "Scanner Options"))
        self.checkBox_followsymlinks.setText(_translate("optionsDialog", "Follow Symlinks"))
        self.checkBox_recursive.setText(_translate("optionsDialog", "Recursive folder selection"))
        self.checkBox_cache.setText(_translate("optionsDialog", "Cache results"))
        self.label_3.setText(_translate("optionsDialog", "File types: (RegEx)"))
        self.label_4.setText(_translate("optionsDialog", "Number of processes: (0 = same as # of cpus):"))
        self.checkBox_cacheraw.setText(_translate("optionsDialog", "Cache raw scanner output"))
        self.checkBox_aucdtect_scan.setText(_translate("optionsDialog", "Run auCDtect on lossless files"))
        self.label_5.setText(_translate("optionsDialog", "Accurate"))
        self.label_6.setText(_translate("optionsDialog", "Fast"))
        self.groupBox_2.setTitle(_translate("optionsDialog", "Advanced"))
        self.checkBox_debug.setText(_translate("optionsDialog", "Debug Output"))
        self.groupBox_3.setTitle(_translate("optionsDialog", "Paths"))
        self.label.setText(_translate("optionsDialog", "Path to mp3guessenc executable:"))
        self.label_2.setText(_translate("optionsDialog", "Path to mediainfo executable:"))
        self.label_7.setText(_translate("optionsDialog", "Path to sox executable:"))
        self.label_11.setText(_translate("optionsDialog", "Path to ffprobe executable:"))
        self.pushButton_mediainfo_path.setText(_translate("optionsDialog", ".."))
        self.pushButton_mp3guessenc_path.setText(_translate("optionsDialog", ".."))
        self.pushButton_sox_path.setText(_translate("optionsDialog", ".."))
        self.groupBox_4.setTitle(_translate("optionsDialog", "Display Options"))
        self.checkBox_savewindowstate.setText(_translate("optionsDialog", "Save window state"))
        self.checkBox_clearfilelist.setText(_translate("optionsDialog", "Clear file list"))
        self.checkBox_spectrogram.setText(_translate("optionsDialog", "Generate spectrogram"))
        self.label_8.setText(_translate("optionsDialog", "(requires sox)"))
        self.label_9.setText(_translate("optionsDialog", "Colour set:"))
        self.checkBox_bitrate_graph.setText(_translate("optionsDialog", "Generate bitrate graph"))
        self.label_10.setText(_translate("optionsDialog", "(requires ffprobe)"))
        self.pushButton_ffprobe_path.setText(_translate("optionsDialog", ".."))

